blank_issues_enabled: false

contact_links:

  - name: Community Slack Team
    url: https://e.lastic.guru/slack/
    about: |-
      Please ask and answer questions here.

  - name: Office Hours
    url: https://e.lastic.guru/office-hours/
    about: |-
      Join us every Wednesday for FREE Office Hours (lunch & learn).